---
- name: Restart crond
  service: name=crond state=restarted
  
- name: rebuild locales database
  command: "{{ item }}"
  with_items:
    - dpkg-reconfigure locales -f noninteractive
    - /usr/sbin/locale-gen

- name: Reconfigure keyboard
  command: "{{ item }}"
  with_items:
    - dpkg-reconfigure -f noninteractive keyboard-configuration
    - dpkg-reconfigure -f noninteractive console-setup
