---
- name: Update APT package list
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade APT dist
  become: yes
  apt:
    upgrade: dist
  register: aptupgrade

- name: restart server if upgraded
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: yes
  ignore_errors: true
  when: aptupgrade.changed

- name: waiting for server to come back after reboot
  wait_for_connection:
    host: "{{ inventory_hostname }}"
    state: started
    port: "{{ common_ssh_port }}"
    delay: 30
    timeout: 300
    connect_timeout: 15
  when: aptupgrade.changed
