---
# Install SoapyRemote

- name: Install libraries and build dependencies
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - avahi-daemon
      - libavahi-client-dev
      - git
      - g++
      - cmake

- name: Clone git
  git:
    repo: "https://github.com/pothosware/SoapyRemote.git"
    dest: "{{ raspbian_soapyremote_directory }}"
    version: "{{ raspbian_soapyremote_git_release_version }}"
  register: gitclone

- name: Remove build dir
  file:
    state: absent
    path: "{{ raspbian_soapyremote_builddir }}"
  when: gitclone.changed

- name: Create empty build dir
  file:
    state: directory
    path: "{{ raspbian_soapyremote_builddir }}"
  when: gitclone.changed

- name: Generate Soapyremote Makefile
  command: cmake ..
  args:
    chdir: "{{ raspbian_soapyremote_builddir }}"
  when: gitclone.changed

- name: Build Soapyremote
  command: make -j4
  args:
    chdir: "{{ raspbian_soapyremote_builddir }}"
  when: gitclone.changed

- name: Make install
  command: make install
  become: yes
  args:
    chdir: "{{ raspbian_soapyremote_builddir }}"
  when: gitclone.changed

# For Debian based systems
- name: Run ldconfid
  command: ldconfig
  become: yes
  args:
    chdir: "{{ raspbian_soapyremote_builddir }}"
  when: gitclone.changed
