---
# Install SDRPlay

- name: Install libraries and build dependencies
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - git
      - g++
      - cmake
      - python

- name: Install pexpect python module
  pip:
    name: pexpect
    state: present

- name: Clone git
  git:
    repo: "https://github.com/pothosware/SoapySDRPlay"
    dest: "{{ raspbian_soapysdrplay_directory }}"
    version: "{{ raspbian_soapysdrplay_git_release_version }}"
  register: gitclone

- name: Copy over driver
  become: yes
  copy:
    src: ./
    # src: ./SoapySDRPlay_RSP_API-RPi-2.13.1.run
    dest: "{{ raspbian_soapysdrplay_directory }}/driver/"
    owner: "{{ common_deploy_user_name }}"
    group: "{{ common_deploy_user_name }}"
    mode: 0744
  register: drivercopy

- name: Install driver
  # become: yes
  # become_user: "{{ common_deploy_user_name }}"
  expect:
    command: sh "{{ raspbian_soapysdrplay_driver_name }}"
    chdir: "{{ raspbian_soapysdrplay_directory }}/driver"
    responses:
      "--More--": " "
      "Press y and RETURN to accept": "y"
  when: drivercopy.changed

# - name: Install driver
#   become: yes
#   become_user: pi
#   command: echo 'y' | sh {{ raspbian_soapysdrplay_driver_name }}
#   args:
#     chdir: "{{ raspbian_soapysdrplay_directory }}/driver/"
#   when: drivercopy.changed

# - name: restart server if upgraded
#   shell: sleep 2 && shutdown -r now "Ansible SDRplay driver installed, restarting"
#   async: 1
#   poll: 0
#   become: yes
#   ignore_errors: true
#   when: drivercopy.changed

# - name: waiting for server to come back after reboot
#   wait_for_connection:
#     host: "{{ inventory_hostname }}"
#     state: started
#     port: "{{ common_ssh_port }}"
#     delay: 30
#     timeout: 300
#     connect_timeout: 15
#   when: drivercopy.changed

- name: Remove build dir
  file:
    state: absent
    path: "{{ raspbian_soapysdrplay_builddir }}"
  when: gitclone.changed

- name: Create empty build dir
  file:
    state: directory
    path: "{{ raspbian_soapysdrplay_builddir }}"
  when: gitclone.changed

- name: Generate Makefile
  command: cmake ..
  args:
    chdir: "{{ raspbian_soapysdrplay_builddir }}"
  when: gitclone.changed

- name: Build
  command: make -j4
  args:
    chdir: "{{ raspbian_soapysdrplay_builddir }}"
  when: gitclone.changed

- name: Make install
  command: make install
  become: yes
  args:
    chdir: "{{ raspbian_soapysdrplay_builddir }}"
  when: gitclone.changed

# For Debian based systems
- name: Run ldconfid
  command: ldconfig
  become: yes
  args:
    chdir: "{{ raspbian_soapysdrplay_builddir }}"
  when: gitclone.changed
