---
# Install SoapySDR

- name: Install libraries and build dependencies
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - git
      - g++
      - cmake
      - libpython-dev
      - python-numpy
      - swig

- name: Clone git
  git:
    repo: "https://github.com/pothosware/SoapySDR.git"
    dest: "{{ raspbian_soapysdr_directory }}"
    version: "{{ raspbian_soapysdr_git_release_version }}"
  register: gitclone

- name: Remove build dir
  file:
    state: absent
    path: "{{ raspbian_soapysdr_builddir }}"
  when: gitclone.changed

- name: Create empty build dir
  file:
    state: directory
    path: "{{ raspbian_soapysdr_builddir }}"
  when: gitclone.changed

- name: Generate SoapySDR Makefile
  command: cmake ..
  args:
    chdir: "{{ raspbian_soapysdr_builddir }}"
  when: gitclone.changed

- name: Build SoapySDR
  command: make -j4
  args:
    chdir: "{{ raspbian_soapysdr_builddir }}"
  when: gitclone.changed

- name: Make install
  command: make install
  become: yes
  args:
    chdir: "{{ raspbian_soapysdr_builddir }}"
  when: gitclone.changed

# For Debian based systems
- name: Run ldconfid
  command: ldconfig
  become: yes
  args:
    chdir: "{{ raspbian_soapysdr_builddir }}"
  when: gitclone.changed
