---
- name: Install required packages
  become: yes
  apt:
    update_cache: yes
    state: present
    name: "{{ packages }}"
  vars:
    packages:
      - unattended-upgrades
      - update-notifier-common

- name: Adjust APT update intervals
  become: yes
  template:
    src: apt_periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
