---
# Install SDRPlay

- name: Update apt cache
  apt: update_cache=yes
  become: yes

- name: Install core library and build dependencies
  apt:
    pkg={{item}}
    state=present
  become: yes
  with_items:
    - git
    - g++
    - cmake

- name: Clone SoapySDRPlay git
  git:
    repo: 'https://github.com/pothosware/SoapySDRPlay'
    dest: /home/pi/SoapySDRPlay
    # version: soapy-sdrplay-0.1.0
  register: gitclone

- name: Copy over SoapySDRPlay driver
  copy:
    src: ./
    # src: ./SoapySDRPlay_RSP_API-RPi-2.13.1.run
    dest: /home/pi/SoapySDRPlay/driver/
    owner: pi
    group: pi
    mode: 0744
  register: drivercopy

- name: Install SoapySDRPlay driver
  become: yes
  become_user: pi
  command: echo "y" | sh SoapySDRPlay_RSP_API-RPi-2.13.1.run
  args:
    chdir: /home/pi/SoapySDRPlay/driver
  when: drivercopy.changed

- name: Remove build dir
  file: state=absent path=/home/pi/SoapySDRPlay/builddir
  when: gitclone.changed

- name: Create empty build dir
  file: state=directory path=/home/pi/SoapySDRPlay/builddir
  when: gitclone.changed

- name: Generate SoapySDRPlay Makefile
  command: cmake ..
  args:
    chdir: /home/pi/SoapySDRPlay/builddir
  when: gitclone.changed

- name: Build SoapySDRPlay
  command: make -j4
  args:
    chdir: /home/pi/SoapySDRPlay/builddir
  when: gitclone.changed

- name: Make install SoapySDRPlay
  command: make install
  become: yes
  args:
    chdir: /home/pi/SoapySDRPlay/builddir
  when: gitclone.changed

# For Debian based systems
- name: Run ldconfid
  command: ldconfig
  become: yes
  args:
    chdir: /home/pi/SoapySDRPlay/builddir
  when: gitclone.changed
