---
- name: Change root password
  become: yes
  user:
    name: root
    password: "{{ common_root_password }}"

- name: Add deploy user
  become: yes
  user:
    name: "{{ common_deploy_user_name }}"
    password: "{{ common_deploy_password }}"
    shell: /bin/bash

- name: Add authorized key for deploy user
  become: yes
  authorized_key:
    user: "{{ common_deploy_user_name }}"
    key: "{{ common_deploy_public_key }}"
    state: present
    validate_certs: yes
    exclusive: yes

- name: Add deploy user to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ common_deploy_user_name }} ALL"
    line: "{{ common_deploy_user_name }} ALL=(ALL) NOPASSWD: ALL"
    # line: "{{ common_deploy_user_name }} ALL=(ALL) ALL"
    state: present
