---
# Base task for configuring a Raspi

- apt: update_cache=yes
  name: 'Update apt cache'
  become: yes
  become_method: sudo

- apt: upgrade=dist
  name: 'Upgrade apt dist'
  become: yes
  become_method: sudo
  notify:
    - Restart server
    - Wait for server to restart

# - name: 'Install packages'
#   apt:
#     pkg={{item}}
#     state=installed
#   become: yes
#   become_method: sudo
#   with_items:
#     - tightvncserver

- name: select default locale
  debconf:
    name: locales
    question: locales/default_environment_locale
    value: en_US.UTF-8
    vtype: select
  notify:
    - rebuild locales database

- name: /etc/locale.gen
  lineinfile:
    dest: /etc/locale.gen
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { regexp: '^#? ?en_US.UTF-8 UTF-8', line: 'en_US.UTF-8 UTF-8', state: present }
  notify:
    - rebuild locales database
    
- name: set timezone to Europe/Stockholm
  timezone:
    name: Europe/Stockholm
  notify:
    - Restart crond

- name: Set keyboard layout
  replace:
    dest: /etc/default/keyboard
    regexp: 'gb'
    replace: 'us'
  notify:
    - Reconfigure keyboard

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify:
    - Restart ssh

- name: Disallow SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify:
    - Restart ssh
