---
# Install SoapyOsmo

- name: Update apt cache
  apt: update_cache=yes
  become: yes

- name: Install core library and build dependencies
  apt:
    pkg={{item}}
    state=present
  become: yes
  with_items:
    - git
    - g++
    - cmake
    - libboost-all-dev

- name: Clone SoapyOsmo git
  git:
    repo: 'https://github.com/pothosware/SoapyOsmo.git'
    dest: /home/pi/SoapyOsmo
    version: soapy-osmo-0.2.5
  register: gitclone

- name: Remove build dir
  file: state=absent path=/home/pi/SoapyOsmo/builddir
  when: gitclone.changed

- name: Create empty build dir
  file: state=directory path=/home/pi/SoapyOsmo/builddir
  when: gitclone.changed

- name: Generate SoapyOsmo Makefile
  command: cmake ..
  args:
    chdir: /home/pi/SoapyOsmo/builddir
  when: gitclone.changed

- name: Build SoapyOsmo
  command: make -j4
  args:
    chdir: /home/pi/SoapyOsmo/builddir
  when: gitclone.changed

- name: Make install SoapyOsmo
  command: make install
  become: yes
  args:
    chdir: /home/pi/SoapyOsmo/builddir
  when: gitclone.changed

# For Debian based systems
- name: Run ldconfid
  command: ldconfig
  become: yes
  args:
    chdir: /home/pi/SoapyOsmo/builddir
  when: gitclone.changed
